### ISSUE TITLE
Вопрос к новому подкасту (если я всё правильно делаю)

### ISSUE THREAD

**Issue by Markmaster** [NoiSeBit/Podcasts#15]
Привет Noise Security Bit Podcast. Начал слушать Ваш подкаст уже с новой итерации, именно в виде NoiSeBit. Понравился очень выпуск, где вы обсуждали работу в области IT и ИБ с ребятами с разных континентов. Там ещё в конце подкаста предлагали всем желающим отправлять резюме и говорили, что работа есть и всё такое. Этот выпуск меня очень вдохновил. Я на самом деле далёк от этого всего, ну там IT и безопасность и прочее. Тем не менее мне всё это интересно. И ещё мне нравятся мобильные устройства, их исследование и ПО для них. Вот я думаю начать писать под мобильные устройства. Но совершенно ничего про это не понимаю. Я знаю, что и "медведя можно научить кататься на велосипеде" и мне кажется что у меня получится тоже. Ну программы писать. Для iOS и Android. Вот у меня вопрос. (Наконец начну его уже %) ). Я хотел бы научиться програмировать. Писать программы. И так, чтобы это было моей специальностью. Ну деньги чтобы зарабатывать. Что мне для этого сделать в плане обучения: начать просто читать литературу в стиле "для чайников" или записаться на какие-нибудь курсы, вечерние там или удалённые по программированию? Если это книга, можете порекомендовать её, если курсы, то можете порекомендовать их? В идеале я бы хотел работать не в России (живу в России на данный момент) а за рубежом, если заканчивать курсы, есть может такие, которые выдают диплом может международного образца, с которым потом могут в нормальную компанию принять или хотя бы пригласить на интервью? Просто я нескольких людей поспрашивал что лучше, курсы там или книгу взять и начать с нуля, многие говорят что книгу и давай пиши уже хоть калькулятор свой. Вот я и думаю, если возьму книгу, и напишу пару аппов, каковы шансы, что меня сначала по этой специальности возьмут на работу сначала тут, в России, а потом, в перспективе, если я смогу себя проявить, и если у меня действительно будет что-то получаться, то и за рубежом? Не станет ли отсутствие диплома профильного ВУЗа или там инденерного образования камнем преткновения в возможном трудоустройстве? Хотелось бы в одном из выпусков Вашего подкаста получить ответ на этот вопрос немного развёрнуто. 

Спасибо. Надеюсь сделал всё с вопросом правильно, потому как других вопросов здесь к подкасту не нашёл, а писать их в твиттер - заебётесь читать %)

**Comment by matrosov** [comment]
Спасибо за ваш отзыв! Цель issues собирать вопросы к готовящихся подкастам и в целом фидбек по проекту ;) Наш проект больше нацелен на людей занимающихся практическими исследованиями в области ИБ, хоть программирование и имеет к этому непосредственное отношение, но я считаю этот вопрос все равно out of scope для нашего проекта. Рекомендую задать его на более профильном ресурсе (rsdn, ...), где вы получите наиболее точный ответ.

**Comment by Markmaster** [comment]
Спасиб!
