### ISSUE TITLE
Noise Security Bit #15 (О поиске уязвимостей и атаках на крипто-софт) 

### ISSUE THREAD

**Issue by matrosov** [NoiSeBit/Podcasts#8]

**Comment by Markmaster** [comment]
Хотел попросить, чтобы в подкасте автор подкаста непосредственно, и его гости, ответили на вопрос, пользуются ли сами крипто-софтом в обыденной жизни, шифруют ли всё подряд, или отлько sensitive data какую-то? Какой у вас вообще уровень паранойи?

**Comment by matrosov** [comment]
+1 обязательно спросим

**Comment by Markmaster** [comment]
В каком выпуске в итоге спросили?

**Comment by matrosov** [comment]
К сожалению этот вопрос остался не отвеченным. Но есть идея записать отдельный подкаст про прайваси и разные степени паранойи. Вот там и спросим ;)
